#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f DataMemoryController.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace --top-module DataMemoryController -I./include ./Memory/*.sv DataMemoryController.sv --exe DataMemoryController_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VDataMemoryController.mk VDataMemoryController

#run executable simulation file
obj_dir/VDataMemoryController
