#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f cache_top.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace --top-module cache_top -I./include ./Cache/*.sv cache_top.sv --exe cache_top_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcache_top.mk Vcache_top

#run executable simulation file
obj_dir/Vcache_top
