#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f top.vcd
rm -f datamem.vcd
rm -f pcreg.vcd
rm -f pcmux.vcd
rm -f datamux.vcd
rm -f alu.vcd
rm -f alu_top.vcd
rm -f mux.vcd
rm -f register.vcd
rm -f ControlUnit.vcd
rm -f ControlPath.vcd
rm -f SignExtend.vcd
rm -f ROM.vcd
rm -f AluEncode.vcd
rm -f ControlDecode.vcd
rm -f ImmDecode.vcd
rm -f InstructionDecode.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top.sv --exe top_tb.cpp
verilator -Wall --cc --trace datamem.sv --exe top_tb.cpp
verilator -Wall --cc --trace datamux.sv --exe top_tb.cpp
verilator -Wall --cc --trace pcreg.sv --exe top_tb.cpp
verilator -Wall --cc --trace pcmux.sv --exe top_tb.cpp
verilator -Wall --cc --trace alu_top.sv --exe top_tb.cpp
verilator -Wall --cc --trace alu.sv --exe top_tb.cpp
verilator -Wall --cc --trace mux.sv --exe top_tb.cpp
verilator -Wall --cc --trace register.sv --exe top_tb.cpp
verilator -Wall --cc --trace ControlUnit.sv --exe top_tb.cpp
verilator -Wall --cc --trace ControlPath.sv --exe top_tb.cpp
verilator -Wall --cc --trace SignExtend.sv --exe top_tb.cpp
verilator -Wall --cc --trace ROM.sv --exe top_tb.cpp
verilator -Wall --cc --trace AluEncode.sv --exe top_tb.cpp
verilator -Wall --cc --trace ControlDecode.sv --exe top_tb.cpp
verilator -Wall --cc --trace ImmDecode.sv --exe top_tb.cpp
verilator -Wall --cc --trace InstructionDecode.sv --exe top_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

#run executable simulation file
obj_dir/Vtop
