#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f pcreg.vcd
rm -f pcmux.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace pcreg.sv --exe pc_tb.cpp
verilator -Wall --cc --trace pcmux.sv --exe pc_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vpcreg.mk Vpcreg

#run executable simulation file
obj_dir/Vpcreg
