#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f datamem.vcd
rm -f datamux.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace datamem.sv --exe mem_tb.cpp
verilator -Wall --cc --trace datamux.sv --exe mem_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vdatamem.mk Vdatamem

#run executable simulation file
obj_dir/Vdatamem
